### ISSUE TITLE
hasIDBPromise() logic issue

### ISSUE THREAD

**Issue by vladimiry** [ProtonMail/mutex-browser#3]
https://github.com/ProtonMail/mutex-browser/blob/cf7746e9dcb13d3837c3eaca86f7b6e713928164/src/index.ts#L12-L18

Looks like `db.onerror` and `db.onsuccess` handlers should resolve the opposite boolean values since right now for most users the consequent code flow will fall back to `cookieMutex` (which demonstrates some issues at least in my case, see #4).

The use case on which I noticed the issue is when session refreshing is happening, somewhere here https://github.com/ProtonMail/proton-shared/blob/137d769c6cd47337593d3a47302eb23245762154/lib/api/helpers/withApiHandlers.js#L111.

**Comment by mmso** [comment]
🤦 Thank you for finding this! I pushed a new version 1.0.4 that should fix it.
